# Generated by Django 2.2.4 on 2019-08-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='episode date')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpmusic.Music')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='episode_date')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpmusic.Music')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='episode date')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='entry_date')),
                ('method', models.CharField(max_length=100, verbose_name='prediction method')),
                ('predicted_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpmusic.Music')),
            ],
        ),
    ]
