# Generated by Django 2.2.4 on 2019-08-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpmusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
